DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    CREATED_AT TIMESTAMP
);

DROP TABLE IF EXISTS url_check;

CREATE TABLE url_check (
    ID SERIAL PRIMARY KEY,
    STATUS_CODE INT,
    TITLE VARCHAR(255),
    H1 VARCHAR(255),
    DESCRIPTION TEXT,
    URL_ID int not null,
    FOREIGN KEY (URL_ID) REFERENCES  urls(ID),
    CREATED_AT TIMESTAMP
);