CREATE TABLE if not exists urls (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    CREATED_AT TIMESTAMP
);

CREATE TABLE if not exists url_check (
    ID SERIAL PRIMARY KEY,
    STATUS_CODE INT,
    TITLE VARCHAR(255),
    H1 VARCHAR(255),
    DESCRIPTION TEXT,
    URL_ID int not null,
    CREATED_AT TIMESTAMP
);